server:
  port: 8765
spring:
  application:#  cloud:
    #    gateway:
    #      server:
    #        webflux:
    #          discovery:
    #            locator:
    #              enableD: true
    #              lower-case-service-id: true

    name: api-gateway



